POST http://localhost:5000/room/enter
Content-Type: application/json

{
    "user1": "123",
    "user2": "44545"
}

###
POST http://localhost:5000/room/enter
Content-Type: application/json

{
    "user2": "123",
    "user1": "44545"
}